services:
  backend:
    build: ./backend
    container_name: vnv_backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    volumes:
      - ./backend/src:/usr/src/app/src
    ports:
      - "3001:3001"
    networks:
        - vnv_net

networks:
  vnv_net:
    external: true
