name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to production
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        run: |
          cd /srv/repos/viernulvier-5
          git pull origin main
          docker compose up -d --build
          docker compose exec vnv_backend npx prisma migrate deploy
